---
- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install python-selinux
  apt:
    name: python-selinux
    state: present
  when: ansible_os_family == 'Debian'
